version: "3"
services:
  pihole:
    image: diginc/pi-hole:alpine
    ports:
      - "${HOST_IP}:53:53/tcp"
      - "${HOST_IP}:53:53/udp"
      - "${HOST_IP}:80:80/tcp"
    environment:
      # enter your docker host IP here
      ServerIP: ${HOST_IP}
      WEBPASSWORD: ${WEBPASSWORD}
    # Add your own custom hostnames you need for your domain
    extra_hosts:
      - "pihole.blake.place:${HOST_IP}"
    volumes:
      - "./pihole:/etc/pihole"
      - "./dnsmasq.d:/etc/dnsmasq.d"
      - "./log/pihole.log:/var/log/pihole.log"
    restart: always
